//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Department { get; set; }
        public string Post { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime Datapreception { get; set; }
        public Nullable<System.DateTime> DataExtensions { get; set; }
    }
}
