//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities : DbContext
    {
        protected HREntities()
            : base("name=HREntities")
        {
            
        }

        private static HREntities _context;

        public static HREntities GetContext()
        {
            if (_context == null)
            {
                _context = new HREntities();
            }
            return _context;
        }
            
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

    
        public virtual DbSet<hr> hr { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
